/* Outlook Express 6 — folder tree, message list, preview pane, compose.
   Import-free on purpose (the build smoke-runner executes this in node);
   main.js injects the shell's window-manager hooks and live-number getters.
   Everything here is cosmetic and local: the statement mail READS the game
   numbers through deps.hooks, it never changes them, and nothing talks to
   the server — smtp.cursor.land does not resolve, which is the point. */

const FOLDERS = ["Inbox", "Outbox", "Sent Items", "Deleted Items", "Drafts"];

/* the OE6 welcome mail, abridged but verbatim in register */
const WELCOME_BODY =
`The solution for all your messaging needs

Outlook Express is the perfect companion for Internet Explorer. E-mail and news reading is easy with these features:

  * E-mail and Newsgroups
  * Multiple accounts and Identities
  * HTML message support
  * Address Book and directory services
  * Offline synchronization
  * Improved Inbox rules

More information about Outlook Express is available in Help.`;

const BULLETIN_BODY =
`Summary
-------
The system crashes when C: fills. All live cursors are banked in full at crash.

Details
-------
Each cursor that dies leaves a corpse file on Local Disk (C:). When the disk
reaches capacity, CURSORS.EXE stops with a STOP error and the epoch ends.
Cursors still live at that moment are banked at their current value. The
system restarts and a new epoch begins.

No user action is required.`;

const SMTP_FAIL =
`The host 'smtp.cursor.land' could not be found. Please verify that you have entered the server name correctly.

Account: 'cursor$net'
Server: 'smtp.cursor.land'
Protocol: SMTP
Port: 25
Secure(SSL): No
Socket Error: 11001
Error Number: 0x800CCC0D`;

export function initOE(deps) {
  const {
    $, IMG, store, sysSnd, playerName, wireWindow,
    openWin, closeWin, showMenu, showError, showConfirm, desk,
    hooks, /* {wallet,rake,tickets,deploys,staked,banked,epoch,contacts} — read-only getters */
  } = deps;

  const sol = u => ((u < 0 ? "-" : "") + (Math.abs(u) / 1000).toFixed(3));
  const when = d => d.toLocaleDateString() + " " + d.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" });

  store.data.oeRead = store.data.oeRead || {};
  const isRead = m => !!(m.read || store.data.oeRead[m.id]);
  const markRead = m => {
    if (isRead(m)) return;
    m.read = 1;
    if (m.sys) { store.data.oeRead[m.id] = 1; store.save(); }
    renderTree(); renderList(); renderStatus();
  };

  const bootAt = new Date();
  function statementBody() {
    const h = hooks;
    return `Account: 'cursor$net'
User: ${playerName()}
Generated: ${when(new Date())}

Wallet balance        ${sol(h.wallet())} SOL
Rakeback accrued      ${(h.rake() / 1000).toFixed(4)} SOL
Rakeback tickets      ${h.tickets().toLocaleString()}
Deploys this session  ${h.deploys()}
Total staked          ${sol(h.staked())} SOL
Total banked          ${sol(h.banked())} SOL
Current epoch         ${h.epoch()}

This statement was generated by CURSORS.EXE from live session data.
No action is required.`;
  }

  /* the three system mails; user mail gets pushed after these */
  const mails = [
    { id: "oe-welcome", sys: 1, folder: "Inbox",
      from: "Microsoft Outlook Express Team", to: "New Outlook Express User",
      subject: "Welcome to Outlook Express 6",
      received: new Date(2001, 7, 24, 8, 0), body: WELCOME_BODY },
    { id: "oe-statement", sys: 1, folder: "Inbox",
      from: "cursor$net", to: playerName(),
      subject: "cursor$net account statement",
      received: bootAt, body: statementBody },
    { id: "oe-bulletin", sys: 1, folder: "Inbox",
      from: "cursor$net", to: playerName(),
      subject: "Release notes: epoch crash behavior",
      received: bootAt, body: BULLETIN_BODY },
  ];
  let seq = 0;
  let curFolder = "Inbox";
  let selId = null;
  let workOffline = false;
  let sortKey = "received", sortAsc = false;

  const inFolder = f => mails.filter(m => m.folder === f);
  const selected = () => mails.find(m => m.id === selId) || null;
  const bodyOf = m => (typeof m.body === "function" ? m.body() : m.body);

  /* ---------- main window rendering ---------- */
  function renderTree() {
    const host = $("#oe-ftree");
    if (!host) return;
    host.innerHTML = "";
    const root = document.createElement("div");
    root.className = "oe-froot";
    root.textContent = "Local Folders";
    host.appendChild(root);
    for (const f of FOLDERS) {
      const unread = inFolder(f).filter(m => !isRead(m)).length;
      const row = document.createElement("div");
      row.className = "oe-frow" + (f === curFolder ? " sel" : "") + (unread ? " unread" : "");
      row.textContent = unread ? `${f} (${unread})` : f;
      row.addEventListener("click", () => { curFolder = f; selId = null; renderAll(); });
      host.appendChild(row);
    }
  }

  function sortedList() {
    const list = inFolder(curFolder).slice();
    const k = sortKey;
    list.sort((a, b) => {
      let r;
      if (k === "received") r = a.received - b.received;
      else r = String(a[k]).toLowerCase() < String(b[k]).toLowerCase() ? -1 : 1;
      return sortAsc ? r : -r;
    });
    return list;
  }

  function renderList() {
    const host = $("#oe-rows");
    if (!host) return;
    const showTo = curFolder === "Outbox" || curFolder === "Sent Items" || curFolder === "Drafts";
    const hd = $("#win-oe .oe-lhead .oe-c-from");
    if (hd) hd.textContent = showTo ? "To" : "From";
    host.innerHTML = "";
    for (const m of sortedList()) {
      const row = document.createElement("div");
      row.className = "oe-row" + (isRead(m) ? "" : " unread") + (m.id === selId ? " sel" : "");
      row.innerHTML = `<span class="oe-c-from"></span><span class="oe-c-subj"></span><span class="oe-c-recv"></span>`;
      row.querySelector(".oe-c-from").textContent = showTo ? m.to : m.from;
      row.querySelector(".oe-c-subj").textContent = m.subject;
      row.querySelector(".oe-c-recv").textContent = when(m.received);
      row.addEventListener("click", () => select(m.id));
      host.appendChild(row);
    }
  }

  function renderPreview() {
    const head = $("#oe-phead"), body = $("#oe-pbody");
    if (!head || !body) return;
    const m = selected();
    if (!m) {
      head.style.display = "none";
      body.textContent = inFolder(curFolder).length
        ? "Select a message to read it."
        : "There are no items in this view.";
      body.classList.add("empty");
      return;
    }
    head.style.display = "";
    head.innerHTML = `<div><b class="oe-pfrom"></b></div><div class="oe-psub"></div>`;
    head.querySelector(".oe-pfrom").textContent = `From: ${m.from}  To: ${m.to}`;
    head.querySelector(".oe-psub").textContent = `Subject: ${m.subject}`;
    body.classList.remove("empty");
    body.textContent = bodyOf(m);
  }

  function renderStatus() {
    const s = $("#oe-status");
    if (!s) return;
    const list = inFolder(curFolder);
    const unread = list.filter(m => !isRead(m)).length;
    s.innerHTML = `<span></span><span class="oe-st-r"></span>`;
    s.firstChild.textContent = `${list.length} message(s), ${unread} unread`;
    s.lastChild.textContent = workOffline ? "Working Offline" : "Working Online";
  }

  function renderTitle() {
    const t = $("#win-oe .title-bar-text");
    if (t) t.textContent = curFolder + " - Outlook Express";
  }

  function renderAll() { renderTree(); renderList(); renderPreview(); renderStatus(); renderTitle(); }

  function select(id) {
    selId = id;
    renderList(); renderPreview();
    const m = selected();
    if (m) markRead(m);
  }

  /* ---------- compose ---------- */
  let composeN = 0;
  function compose(opts) {
    opts = opts || {};
    const id = "win-oe-compose-" + (++composeN);
    const el = document.createElement("div");
    el.className = "window oe-compose";
    el.id = id;
    el.dataset.minw = "320"; el.dataset.minh = "240";
    el.style.left = (140 + composeN * 24) + "px";
    el.style.top = (80 + composeN * 22) + "px";
    el.style.width = "460px"; el.style.height = "360px";
    el.innerHTML = `
      <div class="title-bar">
        <div class="tb-l"><img class="tb-ico" src="${IMG.outlook32}" alt=""><div class="title-bar-text">New Message</div></div>
        <div class="title-bar-controls"><button aria-label="Minimize"></button><button aria-label="Close"></button></div>
      </div>
      <div class="win-body oe-cbody">
        <div class="menubar"><span>File</span><span>Edit</span><span>View</span><span>Insert</span><span>Format</span><span>Tools</span><span>Message</span><span>Help</span></div>
        <div class="oe-toolbar"><button class="oe-tb oe-csend">Send</button></div>
        <div class="oe-cfields">
          <label>To:</label><input class="oe-cto" spellcheck="false">
          <label>Subject:</label><input class="oe-csub" spellcheck="false">
        </div>
        <textarea class="oe-ctext" spellcheck="false"></textarea>
      </div>`;
    desk.appendChild(el);
    const to = el.querySelector(".oe-cto"), sub = el.querySelector(".oe-csub"), txt = el.querySelector(".oe-ctext");
    to.value = opts.to || "";
    sub.value = opts.subject || "";
    txt.value = opts.body || "";
    const retitle = () => { el.querySelector(".title-bar-text").textContent = sub.value.trim() || "New Message"; };
    sub.addEventListener("input", retitle);
    retitle();
    for (const i of [to, sub, txt]) i.addEventListener("keydown", e => e.stopPropagation());

    el.querySelector(".oe-csend").addEventListener("click", () => {
      if (!to.value.trim()) {
        showError("Outlook Express", "You must enter at least one e-mail address.");
        return;
      }
      mails.push({
        id: "oe-user-" + (++seq), folder: "Outbox",
        from: playerName(), to: to.value.trim(),
        subject: sub.value.trim(), received: new Date(),
        body: txt.value, read: 1,
      });
      closeWin(id);
      el.remove();
      renderAll();
    });

    wireWindow(el);
    openWin(id);
    setTimeout(() => { try { (opts.to ? sub : to).focus(); } catch (e) {} }, 0);
  }

  function quoted(m) {
    return "\n\n----- Original Message -----\nFrom: " + m.from +
      "\nSent: " + when(m.received) + "\nSubject: " + m.subject + "\n\n" + bodyOf(m);
  }
  function reply() {
    const m = selected();
    if (!m) return;
    compose({ to: m.from, subject: (/^re:/i.test(m.subject) ? m.subject : "Re: " + m.subject), body: quoted(m) });
  }
  function forward() {
    const m = selected();
    if (!m) return;
    compose({ subject: (/^fw:/i.test(m.subject) ? m.subject : "Fw: " + m.subject), body: quoted(m) });
  }

  /* ---------- send/receive ---------- */
  let srBusy = false;
  function sendRecv() {
    if (srBusy) return;
    if (workOffline) {
      showConfirm("Outlook Express", "You are currently working offline. Do you want to go online now?",
        () => { workOffline = false; renderStatus(); sendRecv(); });
      return;
    }
    srBusy = true;
    const el = document.createElement("div");
    el.className = "window oe-progress";
    el.id = "win-oe-progress";
    el.style.left = "220px"; el.style.top = "180px"; el.style.width = "340px";
    el.innerHTML = `
      <div class="title-bar">
        <div class="tb-l"><img class="tb-ico" src="${IMG.outlook32}" alt=""><div class="title-bar-text">Outlook Express</div></div>
        <div class="title-bar-controls"><button aria-label="Close"></button></div>
      </div>
      <div class="win-body pad oe-pgbody">
        <div class="oe-pgtask">Checking for new messages on 'cursor$net'...</div>
        <div class="oe-pgbar"><i></i></div>
      </div>`;
    desk.appendChild(el);
    wireWindow(el);
    openWin(el.id);
    const bar = el.querySelector(".oe-pgbar i");
    const task = el.querySelector(".oe-pgtask");
    const done = () => { srBusy = false; closeWin(el.id); el.remove(); };
    let p = 0;
    const t = setInterval(() => {
      p = Math.min(100, p + 9 + Math.random() * 13);
      bar.style.width = p + "%";
      if (p < 100) return;
      clearInterval(t);
      const out = inFolder("Outbox");
      if (!out.length) { setTimeout(done, 300); return; }
      task.textContent = `Sending ${out.length} message(s) using 'cursor$net'...`;
      bar.style.width = "0%";
      setTimeout(() => {
        bar.style.width = "40%";
        setTimeout(() => {
          done();               /* the messages stay in the Outbox */
          showError("Outlook Express", SMTP_FAIL);
        }, 700);
      }, 500);
    }, 140);
  }

  /* ---------- delete ---------- */
  function del() {
    const m = selected();
    if (!m) return;
    if (m.folder === "Deleted Items") {
      showConfirm("Outlook Express", "Are you sure you want to permanently delete this message?", () => {
        mails.splice(mails.indexOf(m), 1);
        selId = null;
        renderAll();
      });
      return;
    }
    m.folder = "Deleted Items";
    selId = null;
    renderAll();
  }
  function emptyDeleted() {
    if (!inFolder("Deleted Items").length) return;
    showConfirm("Outlook Express",
      "Are you sure you want to permanently delete all the items in the 'Deleted Items' folder?", () => {
        for (let i = mails.length - 1; i >= 0; i--)
          if (mails[i].folder === "Deleted Items") mails.splice(i, 1);
        if (curFolder === "Deleted Items") selId = null;
        renderAll();
      });
  }

  /* ---------- address book ---------- */
  let addrEl = null;
  function openAddresses() {
    if (!addrEl) {
      addrEl = document.createElement("div");
      addrEl.className = "window oe-addr";
      addrEl.id = "win-oe-addr";
      addrEl.dataset.minw = "260"; addrEl.dataset.minh = "200";
      addrEl.style.left = "260px"; addrEl.style.top = "140px";
      addrEl.style.width = "360px"; addrEl.style.height = "300px";
      addrEl.innerHTML = `
        <div class="title-bar">
          <div class="tb-l"><img class="tb-ico" src="${IMG.outlook32}" alt=""><div class="title-bar-text">Address Book - Main Identity</div></div>
          <div class="title-bar-controls"><button aria-label="Minimize"></button><button aria-label="Close"></button></div>
        </div>
        <div class="win-body oe-abody">
          <div class="oe-lhead"><span class="oe-a-name">Name</span><span class="oe-a-mail">E-Mail Address</span><span class="oe-a-st">Status</span></div>
          <div class="oe-arows"></div>
          <div class="oe-status"><span>Double-click a contact to send mail.</span></div>
        </div>`;
      desk.appendChild(addrEl);
      wireWindow(addrEl);
    }
    const host = addrEl.querySelector(".oe-arows");
    host.innerHTML = "";
    for (const c of (hooks.contacts() || [])) {
      const mail = c.name + "@hotmail.com";
      const row = document.createElement("div");
      row.className = "oe-row";
      row.innerHTML = `<span class="oe-a-name"></span><span class="oe-a-mail"></span><span class="oe-a-st"></span>`;
      row.querySelector(".oe-a-name").textContent = c.name;
      row.querySelector(".oe-a-mail").textContent = mail;
      row.querySelector(".oe-a-st").textContent = c.status || "";
      row.addEventListener("dblclick", () => compose({ to: mail }));
      host.appendChild(row);
    }
    openWin("win-oe-addr");
  }

  /* ---------- find ---------- */
  let findEl = null;
  function openFind() {
    if (!findEl) {
      findEl = document.createElement("div");
      findEl.className = "window oe-find";
      findEl.id = "win-oe-find";
      findEl.dataset.minw = "280"; findEl.dataset.minh = "160";
      findEl.style.left = "300px"; findEl.style.top = "170px";
      findEl.style.width = "380px"; findEl.style.height = "240px";
      findEl.innerHTML = `
        <div class="title-bar">
          <div class="tb-l"><img class="tb-ico" src="${IMG.outlook32}" alt=""><div class="title-bar-text">Find Message</div></div>
          <div class="title-bar-controls"><button aria-label="Close"></button></div>
        </div>
        <div class="win-body oe-fbody">
          <div class="oe-fbar">
            <label>Message:</label>
            <input class="oe-fq" spellcheck="false">
            <button class="xbtn oe-fgo">Find Now</button>
          </div>
          <div class="oe-fres"></div>
        </div>`;
      desk.appendChild(findEl);
      const q = findEl.querySelector(".oe-fq");
      q.addEventListener("keydown", e => { e.stopPropagation(); if (e.key === "Enter") run(); });
      findEl.querySelector(".oe-fgo").addEventListener("click", run);
      wireWindow(findEl);
      function run() {
        const needle = q.value.trim().toLowerCase();
        const host = findEl.querySelector(".oe-fres");
        host.innerHTML = "";
        if (!needle) return;
        const hits = mails.filter(m =>
          (m.from + " " + m.to + " " + m.subject + " " + bodyOf(m)).toLowerCase().includes(needle));
        if (!hits.length) {
          host.innerHTML = `<div class="oe-fnone">There are no messages that match the search criteria.</div>`;
          return;
        }
        for (const m of hits) {
          const row = document.createElement("div");
          row.className = "oe-row";
          row.innerHTML = `<span class="oe-c-from"></span><span class="oe-c-subj"></span>`;
          row.querySelector(".oe-c-from").textContent = m.from;
          row.querySelector(".oe-c-subj").textContent = m.subject + "  (" + m.folder + ")";
          row.addEventListener("dblclick", () => {
            curFolder = m.folder;
            renderAll();
            select(m.id);
            openWin("win-oe");
          });
          host.appendChild(row);
        }
      }
    }
    openWin("win-oe-find");
    setTimeout(() => { try { findEl.querySelector(".oe-fq").focus(); } catch (e) {} }, 0);
  }

  /* ---------- dialogs ---------- */
  function accountsDlg() {
    showError("Internet Accounts",
      "Account: cursor$net (default)\nType: mail\nConnection: Any Available\n\n" +
      "Incoming mail (POP3): pop.cursor.land\nOutgoing mail (SMTP): smtp.cursor.land\n\n" +
      "This account is read-only.", true);
  }
  function about() {
    showError("About Outlook Express", "Outlook Express\nVersion 6.00.2900.2180", true);
  }
  function printMail() {
    showError("Print",
      "No printer is installed. To install a printer, click Start, and then click Printers and Faxes.");
  }

  /* ---------- menus (main window; the delegated menubar handler calls this) ---------- */
  function menus(label) {
    const sel = selected();
    switch (label) {
      case "File": return [
        { label: "New", sub: [
          { label: "Mail Message", action: () => compose() },
          { label: "Folder...", disabled: 1 }] },
        { sep: 1 },
        { label: "Print...", disabled: 1 },
        { sep: 1 },
        { label: "Work Offline", check: workOffline, action: () => { workOffline = !workOffline; renderStatus(); } },
        { sep: 1 },
        { label: "Exit", action: () => closeWin("win-oe") }];
      case "Edit": return [
        { label: "Delete", accel: "Ctrl+D", disabled: !sel, action: del },
        { label: "Empty 'Deleted Items' Folder", disabled: !inFolder("Deleted Items").length, action: emptyDeleted },
        { sep: 1 },
        { label: "Find...", action: openFind }];
      case "View": return [
        { label: "Layout...", disabled: 1 },
        { label: "Sort By", sub: [
          { label: "From", check: sortKey === "from", action: () => { sortKey = "from"; renderList(); } },
          { label: "Subject", check: sortKey === "subject", action: () => { sortKey = "subject"; renderList(); } },
          { label: "Received", check: sortKey === "received", action: () => { sortKey = "received"; renderList(); } },
          { sep: 1 },
          { label: "Ascending", check: sortAsc, action: () => { sortAsc = true; renderList(); } },
          { label: "Descending", check: !sortAsc, action: () => { sortAsc = false; renderList(); } }] }];
      case "Tools": return [
        { label: "Send and Receive", action: sendRecv },
        { sep: 1 },
        { label: "Address Book...", accel: "Ctrl+Shift+B", action: openAddresses },
        { sep: 1 },
        { label: "Accounts...", action: accountsDlg }];
      case "Message": return [
        { label: "New Message", accel: "Ctrl+N", action: () => compose() },
        { sep: 1 },
        { label: "Reply to Sender", accel: "Ctrl+R", disabled: !sel, action: reply },
        { label: "Forward", accel: "Ctrl+F", disabled: !sel, action: forward }];
      case "Help": return [
        { label: "About Outlook Express", action: about }];
    }
    return [{ label: "(nothing here)", disabled: 1 }];
  }

  /* ---------- boot: wire the static window ---------- */
  const win = document.getElementById("win-oe");
  if (win) {
    win.querySelectorAll(".oe-toolbar [data-oe]").forEach(b => b.addEventListener("click", () => {
      switch (b.dataset.oe) {
        case "new": compose(); break;
        case "reply": case "replyall": reply(); break;
        case "forward": forward(); break;
        case "print": printMail(); break;
        case "delete": del(); break;
        case "sendrecv": sendRecv(); break;
        case "addresses": openAddresses(); break;
        case "find": openFind(); break;
      }
    }));
    /* column headers sort, like the real list view */
    const heads = { "oe-c-from": "from", "oe-c-subj": "subject", "oe-c-recv": "received" };
    win.querySelectorAll(".oe-lhead span").forEach(h => h.addEventListener("click", () => {
      const k = heads[h.className];
      if (!k) return;
      if (sortKey === k) sortAsc = !sortAsc; else { sortKey = k; sortAsc = k !== "received"; }
      renderList();
    }));
    renderAll();
  }

  function open() {
    sysSnd("nav", .5);
    renderAll();          /* the statement column shows live-fresh numbers */
    openWin("win-oe");
  }

  return { open, menus, compose };
}
